# ==========================================================
# Copyright (c) 2026 VelocityBots
# All Rights Reserved. 
#
# Project      : VelocityBots API Telegram Music Bot
# Powered By   : ⎯꯭̽𓆩꯭͈〬𝐉͢αη𝐡νί ✗ Μυδί𝛓꯭ ̽🤍͢
# Type         : API Based Telegram Music Bot
#
# Bot          : @JanhvixmusicRobot
# Channel      : https://t.me/VelocityBots
# GitHub       : https://github.com/bishalkumar000001/ArtistMusic
#
# Unauthorized copying, modification, or redistribution
# of this source code without permission is prohibited.
# ==========================================================
services:
  - type: worker
    name: ArtistMusic
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python -m ArtistMusic
    plan: free
