import html
import json
import os
import re
import time
from typing import Optional
import aiohttp

from Elevenyts import config, queue

_PLAYER_PHOTOS: dict[tuple[int, int], str] = {}


def _api(method: str) -> str:
    return f"https://api.telegram.org/bot{config.BOT_TOKEN}/{method}"


def _time(sec: int, duration: int) -> str:
    import time
    sec = max(0, int(sec or 0))
    return time.strftime("%H:%M:%S" if duration >= 3600 else "%M:%S", time.gmtime(sec))


def progress_text(media, timer: Optional[str] = None) -> str:
    duration = int(getattr(media, "duration_sec", 0) or 0)
    if timer:
        return timer
    if not duration:
        return "LIVE"
    played = max(0, min(int(getattr(media, "time", 0) or 0), duration))
    n = 12
    filled = int(round(n * played / duration))
    bar = "━" * filled + "●" + "━" * (n - filled)
    return f"{_time(played, duration)} {bar} {_time(duration, duration)}"


def _clean_base_html(base_html: str) -> str:
    """Make the existing locale player text valid/clean Rich HTML.

    Older locale strings contain <a href={0}>. After .format() this becomes
    <a href=https://...>, which Rich HTML rejects and can display literally.
    Quote such href values and remove blockquote wrappers so the player reads
    like the clean text layout used by the reference player.
    """
    text = base_html or ""

    # Fix malformed unquoted hrefs generated by locale .format().
    text = re.sub(r'<a\s+href=([^"\'>\s]+)>', r'<a href="\1">', text)

    # Keep the useful text but remove the colored quote boxes from the player.
    text = text.replace("<blockquote>", "").replace("</blockquote>", "")
    text = text.replace("<blockquote expandable>", "").replace("</blockquote>", "")

    # Make the metadata easier to read without changing localized wording.
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text


def controls_html(chat_id: int, media, *, timer: Optional[str] = None,
                  playing: bool = True, remove: bool = False) -> str:
    if remove:
        return ""
    state = "pause" if playing else "resume"
    label = "Ⅱ Pause" if playing else "▶ Resume"
    try:
        upcoming = max(0, len(queue.get_queue(chat_id)) - 1)
    except Exception:
        upcoming = 0

    # The elapsed/total time is itself a Rich Message button.  It is a
    # callback button (status) so Telegram treats it as a real button rather
    # than ordinary text.  It intentionally has no action beyond acknowledging
    # the tap; playback controls remain on the next rows.
    p = html.escape(progress_text(media, timer))

    # Rich Message buttons only support Telegram's predefined styles: danger,
    # success, primary, or link.  Rotate the background style every 5 seconds
    # while the track is playing.  The existing player timer calls edit_player
    # frequently, so this changes automatically without another scheduler.
    # When paused, keep a stable palette instead of continuing the animation.
    if playing:
        phase = int(time.time() // 5) % 3
    else:
        phase = 0
    palettes = (
        ("success", "primary", "danger", "success"),
        ("primary", "danger", "success", "primary"),
        ("danger", "success", "primary", "danger"),
    )
    time_style, replay_style, state_style, queue_style = palettes[phase]

    return (
        f'<tg-button-row align="center">'
        f'<tg-button type="callback_data" style="{time_style}" data="controls status {chat_id}">{p}</tg-button>'
        f'</tg-button-row>'
        f'<tg-button-row align="center">'
        f'<tg-button type="callback_data" style="{replay_style}" data="controls replay {chat_id}">↻ Replay</tg-button>'
        f'<tg-button type="callback_data" style="{state_style}" data="controls {state} {chat_id}">{label}</tg-button>'
        f'<tg-button type="callback_data" style="{queue_style}" data="controls skip {chat_id}">» Skip</tg-button>'
        f'</tg-button-row>'
        f'<tg-button-row align="center">'
        f'<tg-button type="callback_data" style="{time_style}" data="controls queue {chat_id}">≡ Queue · {upcoming}</tg-button>'
        f'</tg-button-row>'
    )


def rich_html(base_html: str, chat_id: int, media, *, timer=None,
              playing=True, remove=False) -> str:
    if remove:
        return _clean_base_html(base_html)
    clean = _clean_base_html(base_html)
    # Time is a Rich button, not a normal text/blockquote line.
    return f'{clean}\n\n{controls_html(chat_id, media, timer=timer, playing=playing)}'


async def _request(method: str, data: dict, file_path: Optional[str] = None) -> dict:
    timeout = aiohttp.ClientTimeout(total=90)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        if file_path and os.path.isfile(file_path):
            form = aiohttp.FormData()
            for k, v in data.items():
                form.add_field(k, json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else str(v))
            with open(file_path, "rb") as fp:
                form.add_field("player_cover", fp, filename=os.path.basename(file_path), content_type="image/jpeg")
                async with session.post(_api(method), data=form) as r:
                    result = await r.json(content_type=None)
        else:
            async with session.post(_api(method), json=data) as r:
                result = await r.json(content_type=None)
    if not result.get("ok"):
        raise RuntimeError(result.get("description", f"Telegram {method} failed"))
    return result


async def send_player(chat_id: int, base_html: str, photo, media, *, playing=True) -> int:
    player_html = rich_html(base_html, chat_id, media, playing=playing)
    if photo and os.path.isfile(str(photo)):
        rich = {
            "html": f'<img src="tg://photo?id=player_cover"/>\n{player_html}',
            "media": [{"id": "player_cover", "media": {"type": "photo", "media": "attach://player_cover"}}],
        }
        result = await _request("sendRichMessage", {"chat_id": chat_id, "rich_message": rich}, str(photo))
    else:
        ref = str(photo or config.DEFAULT_THUMB)
        rich = {
            "html": f'<img src="tg://photo?id=player_cover"/>\n{player_html}',
            "media": [{"id": "player_cover", "media": {"type": "photo", "media": ref}}],
        }
        if not ref.startswith(("http://", "https://")):
            rich["html"] = player_html
            rich.pop("media", None)
        result = await _request("sendRichMessage", {"chat_id": chat_id, "rich_message": rich})

    msg = result["result"]
    mid = int(msg["message_id"])
    try:
        photos = msg.get("photo") or []
        if photos:
            _PLAYER_PHOTOS[(chat_id, mid)] = photos[-1].get("file_id")
    except Exception:
        pass
    return mid


async def edit_player(chat_id: int, message_id: int, base_html: str, media, *,
                      timer=None, playing=True, remove=False) -> bool:
    if remove:
        try:
            await _request("deleteMessage", {"chat_id": chat_id, "message_id": message_id})
            _PLAYER_PHOTOS.pop((chat_id, message_id), None)
            return True
        except Exception:
            return False

    photo = _PLAYER_PHOTOS.get((chat_id, message_id))
    rich = {"html": rich_html(base_html, chat_id, media, timer=timer, playing=playing)}
    if photo:
        rich["html"] = f'<img src="tg://photo?id=player_cover"/>\n{rich["html"]}'
        rich["media"] = [{"id": "player_cover", "media": {"type": "photo", "media": photo}}]
    try:
        await _request("editMessageText", {
            "chat_id": chat_id,
            "message_id": message_id,
            "rich_message": rich,
        })
        return True
    except Exception:
        return False


async def edit_player_message(chat_id, message_id, base_html, media, *args, **kwargs):
    return await edit_player(
        chat_id,
        message_id,
        base_html,
        media,
        timer=kwargs.get("timer"),
        playing=kwargs.get("playing", True),
        remove=kwargs.get("remove", False),
    )
